version: 2
updates:
  # Python dependencies configuration
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "python"
      - "backend"
    reviewers:
      - "backend-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10

  # Node.js dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    reviewers:
      - "frontend-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10

  # Docker dependencies configuration
  - package-ecosystem: "docker"
    directory: "/infrastructure/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "devops-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5

  # GitHub Actions dependencies configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "devops-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5